---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  type: NodePort
  selector:
    app: registration-app  # FIXED: Matches Deployment labels
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  # FIXED: Formatting
